Update docs to install Redis v4.0 or later
Redis v4.0 or later is required to create superuser on Centos7. Otherwise it generates this error - 
redis.exceptions.ResponseError: Error running script (call to f_0605214935a9ffcd4b9e5779300302540ff08da4): @user_script:36: @user_script: 36: Unknown Redis command called from Lua script