Added check in views.py to bypass the log messages if the status is success and message is None.
Fixed issue related to edit script ("AttributeError: 'dict' object has no attribute 'append'")